export const dom = {
  accordionTriggers: Array.from(document.querySelectorAll("[data-accordion-target]")),

  docTitle: document.getElementById("docTitle"),
  sourceBadge: document.getElementById("sourceBadge"),
  readingTime: document.getElementById("readingTime"),
  confidencePill: document.getElementById("confidencePill"),
  currentTargetMeta: document.getElementById("currentTargetMeta"),
  sessionPill: document.getElementById("sessionPill"),
  statusBar: document.getElementById("statusBar"),
  statusPercent: document.getElementById("statusPercent"),
  statusProgressWrap: document.getElementById("statusProgressWrap"),
  statusProgressFill: document.getElementById("statusProgressFill"),

  openHistoryBtn: document.getElementById("openHistoryBtn"),
  openAccountBtn: document.getElementById("openAccountBtn"),

  modals: {
    overlay: document.getElementById("modalOverlay"),
    history: document.getElementById("historyModal"),
    account: document.getElementById("accountModal"),
    closeHistoryBtn: document.getElementById("closeHistoryModalBtn"),
    closeAccountBtn: document.getElementById("closeAccountModalBtn"),
  },

  render: {
    formatBadge: document.getElementById("formatBadge"),
    panelTitle: document.getElementById("panelTitle"),
    analysisBasis: document.getElementById("analysisBasis"),
    sourceNote: document.getElementById("sourceNote"),
    introLabel: document.getElementById("introLabel"),
    pointsLabel: document.getElementById("pointsLabel"),
    conclusionLabel: document.getElementById("conclusionLabel"),
    annexLabel: document.getElementById("annexLabel"),
    intro: document.getElementById("intro"),
    keyPoints: document.getElementById("keyPoints"),
    conclusion: document.getElementById("conclusion"),
    annexBlocks: document.getElementById("annexBlocks"),
    copyBtn: document.getElementById("copyBtn"),
    refreshBtn: document.getElementById("refreshBtn"),
  },

  analyze: {
    formatTabs: Array.from(document.querySelectorAll("[data-format]")),
    scopeSelect: document.getElementById("scopeSelect"),
    inspectBtn: document.getElementById("inspectBtn"),
    pickBtn: document.getElementById("pickBtn"),
    analyzeSelectionBtn: document.getElementById("analyzeSelectionBtn"),
    selectionStateTitle: document.getElementById("selectionStateTitle"),
    selectionStateText: document.getElementById("selectionStateText"),
    currentTargetTitle: document.getElementById("docTitle"),
    currentTargetMeta: document.getElementById("currentTargetMeta"),
    formatGuideTitle: document.getElementById("formatGuideTitle"),
    formatGuideSummary: document.getElementById("formatGuideSummary"),
    formatGuideBestFor: document.getElementById("formatGuideBestFor"),
  },

  history: {
    historyMeta: document.getElementById("historyMeta"),
    historyCountBadge: document.getElementById("historyCountBadge"),
    historySearch: document.getElementById("historySearch"),
    historyList: document.getElementById("historyList"),
    clearHistoryBtn: document.getElementById("clearHistoryBtn"),
  },

  settings: {
    backendUrl: document.getElementById("backendUrl"),
    authEmail: document.getElementById("authEmail"),
    authPassword: document.getElementById("authPassword"),
    saveSettingsBtn: document.getElementById("saveSettingsBtn"),
    loginBtn: document.getElementById("loginBtn"),
    registerBtn: document.getElementById("registerBtn"),
    logoutBtn: document.getElementById("logoutBtn"),
    authStateTitle: document.getElementById("authStateTitle"),
    authStateText: document.getElementById("authStateText"),
  },
};
