export const state = {
  currentFormat: "express",
  activeTabId: null,
  activeTabUrl: "",
  activeTabTitle: "",
  lastKnownSelection: null,
  historyItems: [],
  currentResult: null,
  lastRequestPayload: null,
  authToken: "",
  currentUser: null,
  progressStartedAt: 0,
  progressReal: 0,
  progressVisual: 0,
  progressTarget: 0,
  progressLabel: "",
  progressTimer: null,
  activeModal: "",
};
